AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  measurement-backend
  Cloud template for measurement domain

Globals:
  Function:
    Tracing: Active
    CodeUri: ../../target/measurement-backend-lambdas-1.0.0-SNAPSHOT-aws.jar
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    Runtime: java17
    Timeout: 30
    MemorySize: 1024

Resources:
  MeasurementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: development
      Name: Measurement API
      Description: API to expose measurement services

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt MeasurementTable.Arn
        - PolicyName: CloudWatchLogsAccess # Añade esta nueva política
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  GetMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: MeasurementLambdaFunction
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref MeasurementApi
            Path: /measurement
            Method: get

  PostMeasurementFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: MeasurementLambdaFunction
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref MeasurementApi
            Path: /measurement
            Method: post

  MeasurementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MeasurementTable
      AttributeDefinitions:
        - AttributeName: MineZoneID
          AttributeType: S
        - AttributeName: MeasurementDateTimeType
          AttributeType: S
      KeySchema:
        - AttributeName: MineZoneID
          KeyType: HASH  # Partition Key
        - AttributeName: MeasurementDateTimeType
          KeyType: RANGE  # Sort Key
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Springboot sample function"
    Value: !Sub "https://${MeasurementApi}.execute-api.${AWS::Region}.amazonaws.com/development/measurement"
